### ISSUE TITLE
Dependency problem with estree-walker

### ISSUE THREAD

**Issue by spence-novata** [cyco130/vite-plugin-cjs-interop#1]
I'm getting `Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in .../node_modules/vite-plugin-cjs-interop/node_modules/estree-walker/package.json`

I'm fairly certain this is https://github.com/Rich-Harris/estree-walker/issues/26, but with no solution forthcoming on their side I'm wondering how you got this to work?

**Comment by cyco130** [comment]
> I'm wondering how you got this to work?

Seems like I didn't. I probably never tested the CJS build (since Vite SSR defaults to ESM now) :)

Thanks for the heads-up. I'll have a look.

**Comment by cyco130** [comment]
On a second thought, why do you need this plugin if you're building CJS?

**Comment by cyco130** [comment]
Fixed. Looks like `estree-walker` is an ESM only package. So I resorted to doing this:

Replaced:

```ts
import { walk } from "estree-walker";
...
walk(...);
```

with:

```ts
const walker = import("estree-walker");
...
const { walk } = await walker; 
walk(...);
```

Using dynamic imports is the only way to use ESM packages from CJS.

(I still think this particular package doesn't need a CJS build though. I did this out of curiosity.)

**Comment by spence-novata** [comment]
Using `vite-plugin-ssr` on build imports of Mui components deep linked eg `import Box from '@mui/material/Box'` come out on the `default` property.

**Comment by spence-novata** [comment]
I can confirm with this update I can now do `import Box from '@mui/material/Box'` thank you 🙏

**Comment by cyco130** [comment]
> Using `vite-plugin-ssr` on build imports of Mui components deep linked eg `import Box from '@mui/material/Box'` come out on the `default` property.

That makes sense. Let's keep the CJS build then :)
