### ISSUE TITLE
@sentry/react does not appear to get fixed

### ISSUE THREAD

**Issue by gajus** [cyco130/vite-plugin-cjs-interop#22]
My configuration:

```ts
cjsInterop({
  dependencies: ['@sentry/react'],
}),
```

and I am still getting error:

```ts
b8d6ae3d > SyntaxError: [vite] Named export 'withScope' not found. The requested module '@sentry/react' is a CommonJS module, which may not support all module.exports as named exports.
b8d6ae3d > CommonJS modules can always be imported via the default export, for example using:
b8d6ae3d >
b8d6ae3d > import pkg from '@sentry/react';
b8d6ae3d > const {captureException, captureMessage, close, setUser, showReportDialog, withScope} = pkg;
b8d6ae3d >
b8d6ae3d >     at analyzeImportedModDifference (file:///Users/gajus/Developer/contra/gaia/node_modules/.pnpm/vite@5.1.0-beta.2_@types+node@20.10.0_sass@1.69.0/node_modules/vite/dist/node/chunks/dep-BzxBS-ea.js:54262:19)
b8d6ae3d >     at nodeImport (file:///Users/gajus/Developer/contra/gaia/node_modules/.pnpm/vite@5.1.0-beta.2_@types+node@20.10.0_sass@1.69.0/node_modules/vite/dist/node/chunks/dep-BzxBS-ea.js:54213:9)
b8d6ae3d >     at ssrImport (file:///Users/gajus/Developer/contra/gaia/node_modules/.pnpm/vite@5.1.0-beta.2_@types+node@20.10.0_sass@1.69.0/node_modules/vite/dist/node/chunks/dep-BzxBS-ea.js:54108:24)
b8d6ae3d >     at eval (/Users/gajus/Developer/contra/gaia/packages/sentry/src/react.ts:27:13)
b8d6ae3d >     at instantiateModule (file:///Users/gajus/Developer/contra/gaia/node_modules/.pnpm/vite@5.1.0-beta.2_@types+node@20.10.0_sass@1.69.0/node_modules/vite/dist/node/chunks/dep-BzxBS-ea.js:54170:9)
b8d6ae3d > ┌────────────────────────────────────────────────────────────────────────────────────────────────────────┐
b8d6ae3d > │ Error could be a CJS/ESM issue, consider using ssr.noExternal, see https://vike.dev/broken-npm-package │
b8d6ae3d > └────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

If it helps, `@sentry/react` is a dependency of a dependency in the same mono repo, as opposed to a direct dependency.

What debugging information can I provide?

I patched the plugin to produce some debugging information:

```ts
      walk(ast, {
        enter(node) {
          if (node.type === "ImportDeclaration") {
            console.log('>>', node.source.value);

            if (matchesDependencies(node.source.value)) {
              toBeFixed.push(node);

              console.log('>', toBeFixed);
            }
          } else if (node.type === "ImportExpression") {
            if (node.source.type === "Literal" && matchesDependencies(node.source.value)) {
              dynamicImportsToBeFixed.push(node);
            }
          }
        }
      });
```

so it does detect it:

```
e7686f01 > >> @sentry/react
e7686f01 > > [
e7686f01 >   Node {
e7686f01 >     type: 'ImportDeclaration',
e7686f01 >     start: 45,
e7686f01 >     end: 98,
e7686f01 >     loc: SourceLocation { start: [Position], end: [Position] },
e7686f01 >     specifiers: [ [Node], [Node] ],
e7686f01 >     source: Node {
e7686f01 >       type: 'Literal',
e7686f01 >       start: 82,
e7686f01 >       end: 97,
e7686f01 >       loc: [SourceLocation],
e7686f01 >       value: '@sentry/react',
e7686f01 >       raw: "'@sentry/react'"
e7686f01 >     }
e7686f01 >   }
e7686f01 > ]
```

**Comment by cyco130** [comment]
A quick test seems to work.

> If it helps, `@sentry/react` is a dependency of a dependency in the same mono repo, as opposed to a direct dependency.

That must be it. By default, Vite doesn't process SSR dependencies. So your direct dependency will not receive the fix. You can try `ssr.noExternal` like Vike suggests or provide a minimal reproduction so I can have a better understanding of the issue.

**Comment by gajus** [comment]
> You can try ssr.noExternal like Vike suggests or provide a minimal reproduction so I can have a better understanding of the issue.

When adding it to `ssr.noExternal`, then I am getting error `module` is undefined.

Will try to read Vite changelog to see what changed. This was working in Vite `5.0.8` and broke after updating to `5.0.12`. Must have been a chance in default configuration.

**Comment by cyco130** [comment]
What I was suggesting was to add the direct dependency (which I assumed to be ESM) to `ssr.noExternal`. CommonJS modules (like `@sentry/react`) can't be added there without also being added to `ssr.optimizeDeps.include` (or something).

**Comment by gajus** [comment]
_got it_

> What I was suggesting was to add the direct dependency (which I assumed to be ESM) to ssr.noExternal.

Just tried. Still the same.

I am going to close this as it seems to be somewhat specific to our environment.

For anyone else running into this issue, I did manage to get it working by simply updating the code to follow this pattern:

https://github.com/facebook/relay/issues/4548#issuecomment-1901133943

**Comment by cyco130** [comment]
> I am going to close this as it seems to be somewhat specific to our environment.

Glad you worked it out. Feel free to post a repro if you find the time though :)
